<?php

/**
 * @file
 * Swagger module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Symfony\Component\Routing\Route;

/**
 * Implements hook_help().
 */
function swagger_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.swagger':
      $output = '';
      $output .= '<h3>' . t('About Swagger') . '</h3>';
      $output .= '<p>' . t('Generate interactive Swagger documentation for your RESTful API using doctrine annotations.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function swagger_theme() {
  return array(
    'swagger_ui' => array(
      'render element' => 'elements',
    ),
  );
}