swagger_scan.admin:
  path: '/admin/structure/swagger-scan'
  defaults:
    _form: '\Drupal\swagger\Form\SwaggerBatchForm'
    _title: 'Swagger - Scan code'
  requirements:
    _permission: 'administer site configuration'

swagger_basic_documentation.admin:
  path: '/admin/structure/swagger-basic-documentation'
  defaults:
    _form: '\Drupal\swagger\Form\SwaggerBasicDocumentationForm'
    _title: 'Swagger - Basic documentation'
  requirements:
    _permission: 'administer site configuration'

swagger.batch:
  path: '/swagger-batch'
  defaults:
    _controller: '\Drupal\swagger\Controller\SwaggerBatchController::runBatch'
    _title: 'Swagger Batch'
  requirements:
    _permission: 'administer content'

swagger.swaggerui:
  path: '/swagger/swagger-ui'
  defaults:
    _controller: '\Drupal\swagger\Controller\SwaggerController::swaggerUiPage'
  requirements:
    _permission: 'swagger ui'