swagger.admin:
  path: '/admin/structure/swagger'
  defaults:
    _form: '\Drupal\swagger\Form\SwaggerBatchForm'
    _title: 'Swagger'
  requirements:
    _permission: 'administer site configuration'

swagger.batch:
  path: '/swagger-batch'
  defaults:
    _controller: '\Drupal\swagger\Controller\SwaggerBatchController::runBatch'
    _title: 'Swagger Batch'
  requirements:
    _permission: 'administer content'

swagger.swaggerui:
  path: '/swagger/swagger-ui'
  defaults:
    _controller: '\Drupal\swagger\Controller\SwaggerController::swaggerUiPage'
  requirements:
    _permission: 'swagger ui'

swagger.swagger:
  path: '/swagger/swagger-spec'
  defaults:
    _controller: '\Drupal\swagger\Controller\SwaggerController::swaggerAPI'
  methods: [GET]
  requirements:
    _access: 'TRUE'
    _format: 'json'