services:
  config.swagger:
    class: Drupal\swagger\SwaggerScan
    arguments: ['@config.factory', '@logger.channel.swagger']
    
  logger.channel.swagger:
    parent: logger.channel_base
    arguments: ['swagger']