swagger_scan.admin:
  path: '/admin/structure/swagger-scan'
  defaults:
    _form: '\Drupal\swagger\Form\SwaggerScanForm'
    _title: 'Swagger - Scan code'
  requirements:
    _permission: 'administer site configuration'

swagger_basic_documentation.admin:
  path: '/admin/structure/swagger-basic-documentation'
  defaults:
    _form: '\Drupal\swagger\Form\SwaggerBasicDocumentationForm'
    _title: 'Swagger - Basic documentation'
  requirements:
    _permission: 'administer site configuration'

swagger.swaggerui:
  path: '/swagger/swagger-ui'
  defaults:
    _controller: '\Drupal\swagger\Controller\SwaggerPageUI::swaggerUiPage'
  requirements:
    _permission: 'swagger ui'